#!/usr/bin/env bash

sudo systemctl stop snapd
sudo systemctl disable snapd
sudo apt purge snapd
sudo rm -rf ~/snap
sudo rm -rf /snap /var/snap /var/lib/snapd /var/cache/snapd /usr/lib/snapd /root/snap
sudo autoremove -y

sudo apt install -y ca-certificates curl gnupg lsb-release
sudo apt update -y

cd /tmp

# install htop
sudo apt install htop -y
apt-cache policy htop

# install google chrome
sudo wget -vc https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
cat /etc/apt/sources.list.d/google-chrome.list
apt-cache policy google-chrome-stable

# install ms visual studio code
sudo wget -vc https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
sudo apt install code -y
sudo apt update -y
apt-cache policy code

# install remmina - Remote access screen and file sharing to your desktop
sudo apt-add-repository ppa:remmina-ppa-team/remmina-next
sudo apt update -y
sudo apt install remmina remmina-plugin-rdp remmina-plugin-secret -y
apt-cache policy remmina

# install wps office
sudo wget -vc https://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/linux/11664/wps-office_11.1.0.11664.XA_amd64.deb
sudo apt install ./wps-office_11.1.0.11664.XA_amd64.deb
apt-cache policy wps-office

# install thunderbird
sudo apt-get install thunderbird -y
apt-cache policy thunderbird

# install postman
wget -v https://dl.pstmn.io/download/latest/linux64
sudo tar -xvf linux64 -C /usr/bin
echo 'export PATH="$PATH:/usr/bin/Postman"' >> ~/.bashrc
sudo tee /usr/share/applications/Postman.desktop <<"EOF"
[Desktop Entry]
Name=Postman API Tool
GenericName=Postman
Comment=Testing API
Exec=/usr/bin/Postman/Postman
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/usr/bin/Postman/app/resources/app/assets/icon.png
StartupWMClass=Postman
StartupNotify=true
EOF
cp /usr/share/applications/Postman.desktop ~/Desktop/

# install docker
sudo mkdir -p /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo chmod a+r /etc/apt/keyrings/docker.gpg
apt-cache policy docker-ce
sudo apt update -y
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
sudo usermod -aG docker ${USER}
su - ${USER}
groups
sudo wget -vc https://desktop.docker.com/linux/main/amd64/docker-desktop-4.15.0-amd64.deb
sudo apt-get install ./docker-desktop-4.15.0-amd64.deb
docker info
docker compose version
docker version
systemctl --user disable docker-desktop
# install lando
sudo wget https://files.lando.dev/installer/lando-x64-stable.deb
sudo dpkg -i lando-x64-stable.deb -y

# install teamviewer
sudo wget -vc https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
sudo apt install ./teamviewer_amd64.deb -y
apt-cache policy teamviewer

# install localwp
sudo wget -vc https://cdn.localwp.com/releases-stable/6.5.2+6204/local-6.5.2-linux.deb
sudo apt install ./local-6.5.2-linux.deb -y
apt-cache policy local

# install eddy debian package installer for elementary OS
sudo apt install valac libgranite-dev libpackagekit-glib2-dev libunity-dev meson ninja-build libzeitgeist-2.0-dev gettext git -y
git clone https://github.com/donadigo/eddy.git eddy
cd eddy
meson build && cd build
meson configure -Dprefix=/usr
ninja
sudo ninja install -y
cd ../

# install gimp
sudo apt install gimp -y
apt-cache policy gimp

# install inkscape
sudo apt install inkscape  -y
apt-cache policy inkscape

# install android studio - https://launchpad.net/~maarten-fonville/+archive/ubuntu/android-studio
sudo add-apt-repository ppa:maarten-fonville/android-studio -y
sudo apt-get update -y
sudo apt install android-studio -y
apt-cache policy android-studio

# install obs studio
sudo apt install obs-studio -y
apt-cache policy obs-studio

# install videoLan Player
sudo apt install vlc -y
apt-cache policy vlc

# clean up
sudo rm -f google-chrome-stable_current_amd64.deb
sudo rm -f wps-office_11.1.0.11664.XA_amd64.deb
sudo rm -f lando-x64-stable.deb
sudo rm -f teamviewer_amd64.deb
sudo rm -f local-6.5.2-linux.deb

apt list

echo "##########################"
echo "Ready to Rock"
echo "##########################"
