#!/usr/bin/env bash

killall io.elementary.appcenter

# Remove appcenter https://github.com/elementary/appcenter

sudo apt-get purge -y appcenter 
sudo apt-get purge -y appstream-data-pantheon* 
sudo apt-get purge -y appstream-data-pantheon-icons* 
sudo apt-get purge -y appstream-data-pantheon-icons-hidpi* 
sudo apt-get purge -y apt-config-icons-hidpi* 
sudo apt-get purge -y apt-config-icons-large* 
sudo apt-get purge -y apt-config-icons-large-hidpi* 
sudo apt-get purge -y evolution-* 
sudo apt-get purge -y io.elementary.feedback 
sudo apt-get purge -y io.elementary.onboarding 
sudo apt-get purge -y io.elementary.music 
# This might not be found for some reason
sudo apt-get purge -y io.elementary.videos
sudo apt policy appstream
sudo apt-mark hold appstream
sudo apt-get update -y
# Remove me
# sudo apt autoremove
