#!/usr/bin/env bash

flatpak uninstall --all -y
sudo apt-get remove flatpak* -y
sudo apt-get purge flatpak* -y
sudo rm -rf ~/.var
sudo rm -rf ~/.cache/flatpak
sudo rm -rf var/lib/flatpak
sudo rm -rf ~/.local/share/flatpak
sudo systemctl stop snapd
sudo systemctl disable snapd
sudo apt purge snapd
sudo rm -rf ~/snap
sudo rm -rf /snap /var/snap /var/lib/snapd /var/cache/snapd /usr/lib/snapd /root/snap
sudo dpkg --configure -a
sudo rm -r /usr/bin/Postman
sudo rm -r /usr/share/applications/Postman.desktop
sudo rm -r ~/Desktop/Postman.desktop
sudo apt purge google-chrome-stable -y
sudo rm -rf ~/.config/google-chrome
sudo rm -rf ~/.cache/google-chrome
sudo apt purge code -y
sudo rm -rf ~/.vscode
sudo rm -rf ~/.config/Code
sudo apt purge remmina remmina-plugin-rdp remmina-plugin-secret -y
sudo apt purge wps-office wps* -y
sudo rm -rf ~/.config/Kingsoft
sudo rm -rf ~/.config/kingsoft
sudo rm -rf ~/.local/share/Kingsoft
sudo apt purge thunderbird* -y
sudo apt purge lando -y
sudo rm -rf ~/.lando
sudo systemctl stop docker
sudo apt-get purge -y docker-engine docker docker.io docker-ce docker-desktop containerd  
sudo apt-get -y --purge docker-engine docker docker.io docker-ce docker-desktop containerd  
docker rmi $(docker images -a -q)
docker rm $(docker ps -a -f status=exited -q)
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker volume prune
sudo umount /var/lib/docker/
sudo rm -rf /var/lib/docker /etc/docker
sudo rm /etc/apparmor.d/docker
sudo groupdel docker
sudo rm -rf /var/run/docker.sock
sudo rm -rf /usr/bin/docker-compose
sudo rm -rf ~/.docker
sudo apt purge teamviewer -y
sudo rm -rf ~/.config/teamviewer
sudo rm -rf ~/.local/share/teamviewer15
sudo rm -rf ~/.cache/TeamViewer
apt show local
sudo apt purge local -y
sudo rm -rf ~/.config/Local
sudo apt purge gimp -y
sudo apt purge inkscape -y
sudo apt purge android-studio -y
sudo rm -rf ~/.android
sudo rm -rf ~/Android
sudo apt purge obs-studio -y
sudo apt purge vlc -y
sudo apt purge com.github.donadigo.eddy -y
sudo apt autoclean
sudo apt autoremove -y
sudo apt update -y
echo "##########################"
echo "Uninstalled all apps"
echo "##########################"
