#!/usr/bin/env bash

sudo rm -r /usr/bin/Postman
sudo rm -r /usr/share/applications/Postman.desktop
sudo rm -r ~/Desktop/Postman.desktop
sudo apt purge google-chrome-stable -y
cd ~/.config
sudo rm -rf google-chrome
sudo apt purge code -y
sudo rm -rf ~/.vscode
sudo apt purge remmina remmina-plugin-rdp remmina-plugin-secret -y
sudo apt purge wps-office -y
sudo apt purge thunderbird* -y
sudo apt purge lando -y
sudo rm -rf ~/.lando
sudo apt-get purge -y docker-engine docker docker.io docker-ce containerd  
sudo apt-get autoremove -y --purge docker-engine docker docker.io docker-ce containerd  
sudo umount /var/lib/docker/
sudo rm -rf /var/lib/docker /etc/docker
sudo rm /etc/apparmor.d/docker
sudo groupdel docker
sudo rm -rf /var/run/docker.sock
sudo rm -rf /usr/bin/docker-compose
sudo apt purge teamviewer -y
sudo apt purge gimp -y
sudo apt purge inkscape -y
sudo apt purge android-studio -y
sudo apt purge obs-studio -y
sudo apt purge vlc -y
sudo apt autoremove -y
sudo apt update -y
echo "##########################"
echo "Uninstalled all apps"
echo "##########################"
